/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package twentyfortyeight;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void testGameInitialization() {
        Game2048 game = new Game2048();
        assertNotNull("Game should be initialized", game);
    }
}
